#!/bin/sh

TEMP= $(dcos marathon task list --json | grep -n "port" | grep -Eo '[0-9]{1,2}' )
PORT_LINE=$(($a+1))
ENDPOINT_PORT=$(dcos marathon task list --json | sed "$PORT_LINE,$PORT_LINE!d" | sed 's/ //g')
ENDPOINT_IP= $(dcos service | grep chronos | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)





echo "curl -L -H 'curl -L -H 'Content-Type: application/json' -X POST -d @docker.json $ENDPOINT_IP:$ENDPOINT_PORT/scheduler/iso8601" >> /bin/launch.sh
echo "curl -L -X PUT $ENDPOINT_IP:$ENDPOINT_PORT/scheduler/job/$JOB_NAME" >> /bin/launch.sh

